### PR TITLE
Fix issue w/ search

### PR DESCRIPTION
**Pull request by mattsperanza**
[fix] SQL pg error
[fix] Catagory failure in advanced search where an array [nil] was passed 
[fix] search.html.erb to include path_keyword when rendering partial

# Description

Multiple issues came up after fixing the SQL issue. Mostly because the search.html.erb file was different then buyers.html.erb and people added things to _itemcard that caused errors when that partial was used in different contexts. 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

I wasn't able to deploy so we still need a deployment test for the search, but it shouldn't be an issue.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by dtlaurianti — APPROVED** [review]
We need the Gemfile.lock for Heroku, so I don't think we should include that commit when we merge this fix.

**Comment by mattsperanza** [comment]
> I think the `path_keyword` should be `'buyer'` not `'edit_item'`. The change in itemcard was to made to change the button in the itemcard from "detail" to "edit" depending on whether you are in sell tab or buy tab. The edit button will enable any user to edit the item, so it should only be in the sell tab.

Done!

**Review by harooks — APPROVED** [review]

**Review by harooks — COMMENTED** [review]
@dtlaurianti should he undo the remove before I approve the PR?  or is it ok

**Comment by dtlaurianti** [comment]
Yeah it'll just get added the next time someone commits, nbd

**Pull request merged**
