### PR TITLE
Style/search fixes

### PR DESCRIPTION
**Pull request by mattsperanza**
# Description

[style] Restyled all search/index/buy pages. No more multiple flash messages.
[style] Added an itemcard partial.
[fix] search price_range parsing
[feat] new method lets search_explicit search for items based on for_sale status

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tests to come later. Not all cucumber tests pass, but they don't pass in main yet either.

# Checklist:

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by mattsperanza** [comment]
We might consider removing buyers_controller since its current state is very thin.

**Review by dtlaurianti — APPROVED** [review]
Working for me and looks a lot more in line with Sergio's theming.  The code looks good and using the partial will make it more reusable.

**Comment by harooks** [comment]
Are we supposed to have two search bars? Right now there's one in the main page, and then the buys page. Do we even need the one on the main page if we have one in the buy page?

**Comment by mattsperanza** [comment]
They are different search features. The one on the home page doesn't have a catagory search or price search.

**Comment by SergioMEV** [comment]
I agree. The one in the main page is super simple and only searches based on name. So, the other search bar is better for more in-depth searches.

**Comment by SergioMEV** [comment]
lgtm

**Review by SergioMEV — APPROVED** [review]

**Pull request merged**
