### PR TITLE
Create new home page

### PR DESCRIPTION
**Pull request by SergioMEV**
# Description

Adds new homepage with featured items, search bar, and category buttons. Makes the following changes:

- Adds featured and featured_amount_paid to items model
- Adds new Category model that has_many items and updates items to belong_to a category
- Adds simple_search and category_search paths to items_controller
- Adds rating column to users model
- Creates new home controller and home view

### View

Matt_s Marketplace (4)

### Notice
This PR changes the category field in the items model from a string to a reference to a category object. This change causes some views to display the category hash instead of the name and might break some routes. I fixed all the ones that I found and I think that some of the views have to be changed anyways. We can decide how to handle this when we  meet.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?
TBD (I'll make a PR with tests over the weekend)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dtlaurianti** [comment]
image
As you mentioned, the category type change breaks the ability to edit or create items.  I am fine with merging this error and fixing the way everything deals with categories, since we agreed to change categories to a fixed number of categories from strings.

**Review by dtlaurianti — APPROVED** [review]
The homepage is a big upgrade in useability and looks great.  Everything on the homepage seems functional.  I think the creation of a home controller makes sense, and your migrations look well divided out.

**If merged as-is we will have some cleanup to do with categories.**

**Comment by mattsperanza** [comment]
When I try seeding the database I am not able to, but without that it seems like there are errors associated with the catagories when I click on anything.

**Comment by SergioMEV** [comment]
What is the error? Did you drop the db before seeding it again?

**Comment by SergioMEV** [comment]
If you run ` rails db:drop ; rails db:create ; rails db:migrate ; rails db:seed` in your terminal it'll drop the db and create it again with the seed data.

**Review by mattsperanza — APPROVED** [review]
Change requires a db:drop. Looks good!

**Pull request merged**
