### PR TITLE
Created user Model

### PR DESCRIPTION
**Pull request by SergioMEV**
# Description

Created the User model, migrations, views, and controller using the `rails generate scaffold` command. Also, added the username and email attributes to the model as unique indexes. Added log and storage folders to .gitignore as well.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

N/A

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by harooks — APPROVED** [review]

**Comment by dtlaurianti** [comment]
Looks like a good start for our users model...
- Maybe think about splitting the user table creation into separate migrations
- I see it added the ARM version of some gems to Gemfile.lock, how do we deal with that or is that correct?
- We should remove log and storage from git tracking, they are just the rails server logs and the database binaries, we should be using a fixture/factory for testing so the sqllite database probably shouldn't be in git

**Comment by SergioMEV** [comment]
> Looks like a good start for our users model...
> 
> * Maybe think about splitting the user table creation into separate migrations
> * I see it added the ARM version of some gems to Gemfile.lock, how do we deal with that or is that correct?
> * We should remove log and storage from git tracking, they are just the rails server logs and the database binaries, we should be using a fixture/factory for testing so the sqllite database probably shouldn't be in git

I don't think that splitting the user table creation is really necessary. The columns added in the first migration are pretty basic. As for the ARM version of the gems, it looks like in the platforms version of the gemfile it is keeping track of the available platforms, so I think that's fine. It would be interesting to see if `bundle install` adds windows versions when you run it. I'll add the log stuff to the .gitignore.

**Comment by SergioMEV** [comment]
On closer inspection, I think bundle install will definitely handle it fine since the ARM stuff is in the Gemfile.lock and not in the Gemfile

**Comment by mattsperanza** [comment]
I agree I don't think we need separate migrations since all the items are super basic. My computer contains the same Gemfile.lock as shown in Sergio's code and didn't cause any issues for my Mac.

**Review by mattsperanza — APPROVED** [review]

**Pull request merged**
